### ISSUE TITLE
join bot with client

### ISSUE THREAD

**Issue by PoLsKiPaLaCz** [Steveice10/LibBot#3]
i would like bots to join from a specified client like huzuni how do i do this?

**Comment by Steveice10** [comment]
I don't know what Huzuni is or what you're even trying to do. The [example](https://github.com/Steveice10/LibBot/blob/master/example/com/github/steveice10/libbot/example/ExampleBot.java) should suffice to explain how to use this library.

**Comment by PoLsKiPaLaCz** [comment]
a hacked client i have looked at the client
